spring:
  application:
    name: books-api-demo
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
springdoc:
  default-support-form-data: true
  paths-to-match: /api/**
p11:
  masking:
    enabled: true
    mask-style: PARTIAL
    mask-character: "*"
    fields:
      - email
      - phoneNumber