### Add book
< {%
    const ids = [];
    const randomSize = Math.floor(Math.random() * 20) + 1;
    for (let i = 0; i < randomSize; i++) {
        ids.push(i);
    }
    request.variables.set("ids", ids);
%}
POST http://localhost:8080/api/v1/books
Content-Type: application/json

{
  "id": {{ids}},
  "title": "{{$random.book.title}}",
  "author": "{{$random.book.author}}",
  "email": "{{$random.email}}",
  "phoneNumber": "{{$random.phoneNumber.phoneNumber}}"
}

### Get books
GET http://localhost:8080/api/v1/books
Content-Type: application/json

### Get book by ID
< {%
    const ids = [];
    const randomSize = Math.floor(Math.random() * 20) + 1;
    for (let i = 0; i < randomSize; i++) {
        ids.push(i);
    }
    request.variables.set("ids", ids);
%}
GET http://localhost:8080/api/v1/books/{{ids}}
